export const dummyData2 = ()=>{
  let arr1 = [
  //검색페이지 더미데이터
  {
    year: 2023,
    month: 7,
    startDay: 12,
    endDay: 16,
    workTitle: "휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 10,
    startDay: 1,
    endDay: 31,
    workTitle: "가을여행 준비",
  },
  {
    year: 2023,
    month: 12,
    startDay: 10,
    endDay: 20,
    workTitle: "크리스마스 트리 구입",
  },
  {
    year: 2023,
    month: 1,
    startDay: 15,
    endDay: 25,
    workTitle: "신년 다이어리 작성",
  },
  {
    year: 2023,
    month: 6,
    startDay: 5,
    endDay: 15,
    workTitle: "여름 휴가 예약",
  },
  {
    year: 2023,
    month: 3,
    startDay: 10,
    endDay: 31,
    workTitle: "봄 꽃구경 가기",
  },
  {
    year: 2023,
    month: 8,
    startDay: 20,
    endDay: 30,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 4,
    startDay: 1,
    endDay: 10,
    workTitle: "방학 계획 세우기",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 캠핑 예약",
  },
  {
    year: 2023,
    month: 9,
    startDay: 1,
    endDay: 20,
    workTitle: "가을 농산물 구매",
  },
  {
    year: 2023,
    month: 2,
    startDay: 15,
    endDay: 25,
    workTitle: "발렌타인데이 선물 준비",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 10,
    workTitle: "크리스마스 선물 구매",
  },
  {
    year: 2023,
    month: 7,
    startDay: 5,
    endDay: 15,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "하계 방학 준비",
  },
  {
    year: 2023,
    month: 3,
    startDay: 1,
    endDay: 31,
    workTitle: "봄 꽃구경 가기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 12,
    startDay: 10,
    endDay: 25,
    workTitle: "크리스마스 계획 세우기",
  },
  {
    year: 2023,
    month: 7,
    startDay: 1,
    endDay: 15,
    workTitle: "휴가 예약",
  },
  {
    year: 2023,
    month: 5,
    startDay: 20,
    endDay: 30,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 3,
    startDay: 1,
    endDay: 15,
    workTitle: "봄 화장품 구매",
  },
  {
    year: 2023,
    month: 8,
    startDay: 5,
    endDay: 20,
    workTitle: "여름 여행 계획 세우기",
  },
  {
    year: 2023,
    month: 6,
    startDay: 1,
    endDay: 15,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 1,
    startDay: 5,
    endDay: 25,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2023,
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    year: 2023,
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    year: 2023,
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    year: 2023,
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    year: 2023,
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    year: 2023,
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    year: 2023,
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    year: 2023,
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    year: 2022,
    month: 12,
    startDay: 1,
    endDay: 5,
    workTitle: '크리스마스 트리 구입',
  },
  {
    year: 2022,
    month: 12,
    startDay: 7,
    endDay: 12,
    workTitle: '크리스마스 계획 세우기',
  },
  {
    year: 2022,
    month: 12,
    startDay: 15,
    endDay: 20,
    workTitle: '크리스마스 준비',
  },
  {
    year: 2022,
    month: 12,
    startDay: 22,
    endDay: 27,
    workTitle: '여행 준비',
  },
  {
    year: 2022,
    month: 12,
    startDay: 28,
    endDay: 31,
    workTitle: '새해 준비',
  },
  {
    year: 2022,
    month: 12,
    startDay: 10,
    endDay: 14,
    workTitle: '모임 준비',
  },
  {
    year: 2022,
    month: 12,
    startDay: 19,
    endDay: 23,
    workTitle: '시험 준비',
  },
  {
    year: 2022,
    month: 12,
    startDay: 27,
    endDay: 30,
    workTitle: '공부 준비',
  },
  {
    year: 2022,
    month: 12,
    startDay: 4,
    endDay: 8,
    workTitle: '스포츠 대회 준비',
  },
  {
    year: 2022,
    month: 12,
    startDay: 18,
    endDay: 22,
    workTitle: '프로젝트 발표 준비',
  },
  {
    year: 2024,
    month: 1,
    startDay: 3,
    endDay: 8,
    workTitle: '크리스마스 준비',
  },
  {
    year: 2024,
    month: 1,
    startDay: 10,
    endDay: 15,
    workTitle: '공부 준비',
  },
  {
    year: 2024,
    month: 1,
    startDay: 17,
    endDay: 22,
    workTitle: '여행 준비',
  },
  {
    year: 2024,
    month: 1,
    startDay: 2,
    endDay: 7,
    workTitle: '워크샵 준비',
  },
  {
    year: 2024,
    month: 1,
    startDay: 13,
    endDay: 18,
    workTitle: '프로젝트 계획 세우기',
  },
  {
    year: 2024,
    month: 1,
    startDay: 25,
    endDay: 30,
    workTitle: '신년 파티 준비',
  },
  {
    year: 2024,
    month: 1,
    startDay: 7,
    endDay: 10,
    workTitle: '동아리 활동 준비',
  },
  {
    year: 2024,
    month: 1,
    startDay: 20,
    endDay: 23,
    workTitle: '면접 준비',
  },
  {
    year: 2024,
    month: 1,
    startDay: 28,
    endDay: 31,
    workTitle: '자격증 시험 준비',
  },
  {
    year: 2024,
    month: 1,
    startDay: 11,
    endDay: 15,
    workTitle: '학업 준비',
  }
];
const filteredArr1 = arr1.filter((event, index, self) => {
  // 배열에서 현재 객체와 동일한 모든 객체들의 인덱스를 찾습니다.
  const duplicateIndexes = self.reduce((acc, obj, currentIndex) => {
    if (
      obj.year === event.year &&
      obj.month === event.month &&
      obj.startDay === event.startDay &&
      obj.endDay === event.endDay &&
      obj.workTitle === event.workTitle &&
      currentIndex !== index // 현재 객체 자신을 제외합니다.
    ) {
      acc.push(currentIndex);
    }
    return acc;
  }, []);

  // 중복된 객체가 존재하지 않으면 true를 반환하여 유지됩니다.
  return duplicateIndexes.length === 0;
});

// 결과 출력
return filteredArr1;
}
