export const dummyData2 = [
  //검색페이지 더미데이터
  {
    month: 7,
    startDay: 12,
    endDay: 16,
    workTitle: "휴가 계획 세우기",
  },
  {
    month: 10,
    startDay: 1,
    endDay: 31,
    workTitle: "가을여행 준비",
  },
  {
    month: 12,
    startDay: 10,
    endDay: 20,
    workTitle: "크리스마스 트리 구입",
  },
  {
    month: 1,
    startDay: 15,
    endDay: 25,
    workTitle: "신년 다이어리 작성",
  },
  {
    month: 6,
    startDay: 5,
    endDay: 15,
    workTitle: "여름 휴가 예약",
  },
  {
    month: 3,
    startDay: 10,
    endDay: 31,
    workTitle: "봄 꽃구경 가기",
  },
  {
    month: 8,
    startDay: 20,
    endDay: 30,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 4,
    startDay: 1,
    endDay: 10,
    workTitle: "방학 계획 세우기",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 캠핑 예약",
  },
  {
    month: 9,
    startDay: 1,
    endDay: 20,
    workTitle: "가을 농산물 구매",
  },
  {
    month: 2,
    startDay: 15,
    endDay: 25,
    workTitle: "발렌타인데이 선물 준비",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 10,
    workTitle: "크리스마스 선물 구매",
  },
  {
    month: 7,
    startDay: 5,
    endDay: 15,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "하계 방학 준비",
  },
  {
    month: 3,
    startDay: 1,
    endDay: 31,
    workTitle: "봄 꽃구경 가기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 12,
    startDay: 10,
    endDay: 25,
    workTitle: "크리스마스 계획 세우기",
  },
  {
    month: 7,
    startDay: 1,
    endDay: 15,
    workTitle: "휴가 예약",
  },
  {
    month: 5,
    startDay: 20,
    endDay: 30,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 3,
    startDay: 1,
    endDay: 15,
    workTitle: "봄 화장품 구매",
  },
  {
    month: 8,
    startDay: 5,
    endDay: 20,
    workTitle: "여름 여행 계획 세우기",
  },
  {
    month: 6,
    startDay: 1,
    endDay: 15,
    workTitle: "여름 바다 여행",
  },
  {
    month: 1,
    startDay: 5,
    endDay: 25,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
  {
    month: 5,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 계획 세우기",
  },
  {
    month: 9,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 휴가 예약",
  },
  {
    month: 2,
    startDay: 1,
    endDay: 10,
    workTitle: "발렌타인데이 데이트 예약",
  },
  {
    month: 11,
    startDay: 5,
    endDay: 15,
    workTitle: "가을 나들이",
  },
  {
    month: 8,
    startDay: 1,
    endDay: 20,
    workTitle: "여름 바다 여행",
  },
  {
    month: 6,
    startDay: 10,
    endDay: 20,
    workTitle: "여름 휴가 준비",
  },
  {
    month: 1,
    startDay: 1,
    endDay: 15,
    workTitle: "신년 목표 세우기",
  },
  {
    month: 12,
    startDay: 1,
    endDay: 31,
    workTitle: "새해 준비",
  },
];
